name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, lint, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test --maxWorkers=50% --silent
        env:
          CI: true
